LPAREN: "("
RPAREN: ")"
NOT: "!" | "~" | "\neg"
AND: "&" | "\wedge"
OR: "|" | "\vee"
IMP: "=>" | "\implies"
IFF: "<=>" | "\iff"
LITERAL: /[a-zA-Z]+/

?literal:   LITERAL                 -> on_literal
?iffexpr:   impexpr
          | impexpr IFF iffexpr     -> on_iff
?impexpr:   orexpr
          | orexpr IMP impexpr      -> on_or
?orexpr:    andexpr
          | andexpr OR orexpr       -> on_and
?andexpr:   notexpr
          | notexpr AND andexpr     -> on_and
?notexpr:   parenexpr
          | NOT parenexpr           -> on_not
?parenexpr: literal
          | LPAREN iffexpr RPAREN

?boolexpr:  iffexpr                 -> on_result

%import common.WS
%ignore WS
